
USE project2_db;
INSERT INTO `food_truck` (`id`,`foodtruck_name`,`descr`,`cuisine`,`location`,`contact`,`date`) VALUES (1,'The Funnel Fairy','Funnel Cakes','Desserts/Treats','','678-541-5555','2018-05-29 18:42:20');
INSERT INTO `food_truck` (`id`,`foodtruck_name`,`descr`,`cuisine`,`location`,`contact`,`date`) VALUES (2,'Doggone Truck','Hot Dogs, Corn Dogs, where everything is barking!','American','','678-541-5556','2018-05-29 18:42:20');
INSERT INTO `food_truck` (`id`,`foodtruck_name`,`descr`,`cuisine`,`location`,`contact`,`date`) VALUES (3,'The Taco Truck','Tacos & Tequilla','Mexican','','678-541-5557','2018-05-29 18:42:20');
INSERT INTO `food_truck` (`id`,`foodtruck_name`,`descr`,`cuisine`,`location`,`contact`,`date`) VALUES (4,'Flatbreads','Specialty Flatbreads and Pizza','Italian','','678-541-5558','2018-05-29 18:42:20');
INSERT INTO `food_truck` (`id`,`foodtruck_name`,`descr`,`cuisine`,`location`,`contact`,`date`) VALUES (5,'Holy Shrimp!','Shrimp in dozens of varieties','Seafood','','678-541-5559','2018-05-29 18:42:20');
INSERT INTO `food_truck` (`id`,`foodtruck_name`,`descr`,`cuisine`,`location`,`contact`,`date`) VALUES (6,'Chick a Stick','Chicken and Waffles on a Stick','American','','678-541-5560','2018-05-29 18:42:20');
INSERT INTO `food_truck` (`id`,`foodtruck_name`,`descr`,`cuisine`,`location`,`contact`,`date`) VALUES (7,'Sushi Truck','We have a truck full of Sushi','Sushi','','678-541-5561','2018-05-29 18:42:20');
INSERT INTO `food_truck` (`id`,`foodtruck_name`,`descr`,`cuisine`,`location`,`contact`,`date`) VALUES (8,'Take-A-Cake','Cake Slices on the go','Desserts/Treats','','678-541-5562','2018-05-29 18:42:20');
INSERT INTO `food_truck` (`id`,`foodtruck_name`,`descr`,`cuisine`,`location`,`contact`,`date`) VALUES (9,'Burger Bus','Beef, Turkey or Tofu... we got you','American','','678-541-5563','2018-05-29 18:42:20');
INSERT INTO `food_truck` (`id`,`foodtruck_name`,`descr`,`cuisine`,`location`,`contact`,`date`) VALUES (10,'Truckpotle','Burritos, Burrito Bow, you know','Mexican','','678-541-5564','2018-05-29 18:42:20');
INSERT INTO `food_truck` (`id`,`foodtruck_name`,`descr`,`cuisine`,`location`,`contact`,`date`) VALUES (11,'Meatball Madness','Meatballs on a stick','Italian','','678-541-5565','2018-05-29 18:42:20');
INSERT INTO `food_truck` (`id`,`foodtruck_name`,`descr`,`cuisine`,`location`,`contact`,`date`) VALUES (12,'Truck Lobster','We serve delicious lobster, from a truck.','Seafood','','678-541-5566','2018-05-29 18:42:20');


INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (1,1,'Classic Funnel Cake','Classic Funnel Cake with Powdered Sugar',3.50);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (2,1,'Strawberry Funnel Cake','Classic Funnel Cake with Strawberry Topping',4.00);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (3,1,'Cinnamon Funnel Cake','Classic Funnel Cake topped with Cinnamon Sugar',4.00);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (4,2,'Classic Hot Dog','Classic Hot Dog with condiments',4.00);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (5,2,'Chicago Dog','Classic Dog with Chili and Veggies',5.00);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (6,2,'Corn Dog','A jumbo dog breaded and fried to perfection',5.00);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (7,3,'Chicken Taco','Grilled Chicken Taco',3.00);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (8,3,'Steak Taco','Marinated Steak Taco',4.00);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (9,3,'Shrimp Taco','Fried Shrimp Taco',4.00);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (10,4,'Chicken Flatbread','Chicken with your choice of Veggies Flatbread',7.00);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (11,4,'Hawaiian','Chicken and Pineapple Flatbread',7.00);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (12,4,'Philly','Grilled Steak and Cheese Flatbread',9.00);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (13,5,'Shrimp Scampi','Shrimp Scampi',8.00);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (14,5,'Fried Shrimp','Fried Shrimp',8.00);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (15,5,'Grilled Shrimp','Grilled Shrimp',8.00);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (16,6,'Classic Chicken and Waffle','Classic Chicken and Waffle hot on a stick',9.50);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (17,6,'Jerk Chicken and Waffle','Jerk Chicken and Waffle hot on a stick',10.00);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (18,6,'Buffalo Chicken and Waffle','Buffalo Chicken and Waffle hot on a stick',10.00);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (19,7,'Philadelphia Roll','Salmon, cream cheese and avocado',12.00);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (20,7,'California Roll','Avocado, cucumber and crab',12.00);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (21,7,'Spicy Tuna Roll','Tuna mixed with hot sauce infused mayonaise',12.00);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (22,8,'Cake Slices','Yellow, Chocolate, Carrot and Red Velvet',5.00);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (23,8,'Cup Cakes','Yellow, Chocolate, Carrot and Red Velvet',3.00);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (24,8,'Cake Pops','Yellow, Chocolate, Carrot and Red Velvet',2.00);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (25,9,'Beef Burger','Quarter pound beef burger any way you like it!',8.00);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (26,9,'Turkey Burger','Quarter pound turkey burger served your way.',8.00);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (27,9,'Tofu Burger','Marinated Grilled Tofu burger with your choice of toppings',8.50);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (28,10,'Burito','Grilled Steak, Chicken or Tofu with your choice of add-ins compiled in a beautiful tortilla',7.00);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (29,10,'Burito Bowl','Grilled Steak, Chicken or Tofu with your choice of add-ins compiled in a big ol bowl',7.00);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (30,10,'Chips and Guac','Homemade Guacomole and fresh chips',4.00);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (31,11,'Italian Style Meatball','Homemade Beef Meaball covered in Classic Marinara Sauce, served on a stick',3.00);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (32,11,'Southern Style Meatball','Homemade Beef Meaball covered in Gravy, served on a stick',3.00);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (33,11,'Turkey Meatball','Homemade Turkey Meatball with your choice of sauce',3.00);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (34,12,'Lobster Roll','Fresh lobster  served on a grilled hot dog-style bun',14.00);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (35,12,'Crab Legs','Steamed crab legs',12.00);
INSERT INTO `truck_menu` (`id`,`truck_id`,`menu_item`,`menu_description`,`price`) VALUES (36,12,'Lobster Bisque','Homemade bisque from fresh lobster',10.00);
